version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: custom_orm_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: custom_orm_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom_orm_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: custom_orm_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - custom_orm_network

volumes:
  postgres_data:

networks:
  custom_orm_network:
    driver: bridge 